version: '3.8'
services:
  web:
    container_name: desafio-dinherow
    build: ./docker
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:Multilaser42@database:5432/desafio-dinherow
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: postgres-desafio-dinherow
    image: postgres:13.3
    environment:
      - POSTGRES_DB=desafio-dinherow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Multilaser42
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - '3002:5432'